# Generated by Django 3.1.7 on 2021-04-12 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分類名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌名稱')),
                ('label', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='materials', to='Stock.label', verbose_name='分類')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='單位名稱')),
                ('sign', models.CharField(max_length=4, verbose_name='單位符號')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockDate', models.DateField(auto_now=True, verbose_name='進貨時間')),
                ('expiryDate', models.DateField(blank=True, null=True, verbose_name='有效期限')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='庫存')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.material', verbose_name='原料')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Stock.unit', verbose_name='單位'),
        ),
    ]
