# Generated by Django 3.1.7 on 2021-04-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='顧客姓名')),
                ('phone', models.CharField(max_length=15, verbose_name='電話')),
                ('passcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='暗號')),
                ('gender', models.CharField(choices=[('M', 'Female'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='性別')),
                ('age', models.IntegerField(verbose_name='年齡')),
            ],
        ),
    ]
