# Generated by Django 3.1.7 on 2021-04-12 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分類名稱')),
                ('customerAction', models.BooleanField(default=True, verbose_name='顧客操作')),
                ('visible', models.BooleanField(default=True, verbose_name='顯示')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='星期名稱')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='狀態名稱')),
                ('itemType', models.CharField(choices=[('N', 'Normal'), ('W', 'Special Week'), ('S', 'Special'), ('E', 'Weekend'), ('O', 'Off')], max_length=2, verbose_name='狀態')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='開始日期')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('week', models.ManyToManyField(blank=True, to='Menu.Week', verbose_name='販售星期')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='餐點名稱')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Menu/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='價格')),
                ('description', models.CharField(max_length=50, verbose_name='描述')),
                ('menu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='menuID', to='Menu.menu', verbose_name='目錄分類')),
                ('menuSet', models.ManyToManyField(blank=True, to='Menu.MenuItem', verbose_name='套餐內容')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Menu.status', verbose_name='上架狀態')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='數量')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.material', verbose_name='原料')),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='Menu.menuitem', verbose_name='餐點')),
            ],
            options={
                'unique_together': {('menuItem', 'material')},
            },
        ),
    ]
