# Generated by Django 3.1.7 on 2021-04-15 00:33

import Menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Menu/', validators=[Menu.models.validate_file_size]),
        ),
    ]
